---
# Deploy default package configuration files
# asdf automatically reads these files when installing new language versions

- name: Deploy Ruby default gems
  template:
    src: default-gems.j2
    dest: "{{ ansible_env.HOME }}/.default-gems"
    mode: '0644'

- name: Deploy Node.js default packages
  template:
    src: default-npm-packages.j2
    dest: "{{ ansible_env.HOME }}/.default-npm-packages"
    mode: '0644'

- name: Deploy Python default packages
  template:
    src: default-python-packages.j2
    dest: "{{ ansible_env.HOME }}/.default-python-packages"
    mode: '0644'

- name: Deploy Elixir default packages
  template:
    src: default-elixir-packages.j2
    dest: "{{ ansible_env.HOME }}/.default-elixir-packages"
    mode: '0644'

- name: Deploy Go default packages
  template:
    src: default-golang-packages.j2
    dest: "{{ ansible_env.HOME }}/.default-golang-packages"
    mode: '0644'

- name: Deploy Rust default crates
  template:
    src: default-cargo-crates.j2
    dest: "{{ ansible_env.HOME }}/.default-cargo-crates"
    mode: '0644'

# Note: asdf automatically installs these packages when installing new language versions
# For existing versions, users can:
# - Run: asdf reshim <language>
# - Reinstall the version to trigger package installation
